config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  root 'blogs#index'
  resources :users
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :blogs do
    resources :comments, only: [:create, :destroy]
  end
  #get 'users/index'
  #get 'users/new'
  #get 'users/create'
  #get 'users/show'
  #get 'users/edit'
  #get 'users/update'
  #get 'users/destroy'
  
  #get 'blogs/index'
  #get 'blogs/new'
  #get 'blogs/create'
  #get 'blogs/show'
  #get 'blogs/edit'
  #get 'blogs/update'
  #get 'blogs/destroy'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user 
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog
  validates :user, presence: true
  validates :blog, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token
    before_save { self.email = email.downcase }

    validates :name, presence: true
    validates :name, uniqueness: true

    validates :email, presence: true
    validates :email, uniqueness: true

    validates :password, presence: true, length: { minimum: 6 }
    has_secure_password
    has_many :comments
    def authenticated?(remember_token)
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def User.new_token # ランダムなトークンを返す
        SecureRandom.urlsafe_base64
    end

    def remember # 永続セッションのためにユーザーをデータベースに記憶する
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    def User.digest(string) # 渡された文字列のハッシュ値を返す
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def forget
        update_attribute(:remember_digest, nil)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
 include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all.order(created_at: "DESC")
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
   if @blog.save
    flash[:success] = "記事の登録に成功しました"
    redirect_to action: :show, id: @blog.id
   else
    flash[:danger] = "記事の登録に失敗しました"
    render :new
   end
  end

  def show
    @blog = Blog.find(params[:id])
    @comments = Comment.where(blog_id: params[:id])
    @comment = @comments.build
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
   if @blog.update_attributes(blog_params)
    flash[:success] = "記事の更新に成功しました"
    redirect_to action: :show, id: @blog.id
   else
    flash[:danger] = "記事の更新に失敗しました"
    render :edit
   end
  end

  def destroy
    Blog.find(params[:id]).destroy
    flash[:success] = "記事を削除しました"
    redirect_to blogs_path
  end

  private
   def blog_params
    params.require(:blog).permit(:id,:title,:content)
   end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :authenticate_user!

  def create
    blog = Blog.find(params[:blog_id])
    @comment = blog.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
     flash[:success] = "コメントを投稿しました"
     redirect_back(fallback_location: root_path)
    else
     flash[:danger] = "コメントを投稿できませんでした"
     redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    Comment.find(params[:comment_id]).destroy
    flash[:success] = "コメントを削除しました"
    redirect_back(fallback_location: root_path)
  end

 private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email:params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash[:danger] = "ログインに失敗しました"
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "会員登録に成功しました"
      redirect_to @user
    else
      flash[:danger] = "会員登録に失敗しました"
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
 
  def authenticate_user!
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/create.html.erb
<h1>Blogs#create</h1>
<p>Find me in app/views/blogs/create.html.erb</p>

app/views/blogs/destroy.html.erb
<h1>削除しました</h1>
<div>
  <%= link_to "戻る", blogs_path %>
</div>

app/views/blogs/edit.html.erb
<h1>ブログ修正画面</h1>

<%= form_for(@blog) do |f| %>
  <%= flash[:success] %>
  <p>
  <%= f.label :title,"タイトル" %>
  <%= f.text_field :title %>
  </p>
  <p>
  <%= f.label :content,"コンテンツ" %>
  <%= f.text_field :content %>
  </p>
  <p>
  <%= f.submit "変更", class: "btn btn-success" %>
  <%= link_to "戻る", blogs_path, class: "btn btn-default" %>
  </p>
<% end %>

app/views/blogs/index.html.erb
<h1>ブログ一覧表</h1>

  <% if logged_in? %>
    <div>
      <%= link_to "新規投稿画面", new_blog_path %>
    </div>
  <% end %>
  <table border ="1">
    <tr align='left'>
      <th>No</th>
      <th>タイトル</th>
      <th>コンテンツ</th>
      <% if logged_in? %>
        <th>編集リンク</th>
        <th>削除リンク</th>
      <% end %>
    </tr>

    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.id %></td>
        <td><%= link_to blog.title, blog_path(:id => blog.id) %></td>
        <td><%= blog.content %></td>
        <% if logged_in? %>
        <td><%= link_to "編集", edit_blog_path(:id => blog.id) %></td>
        <td><%= link_to "削除", blog_path(:id => blog.id), method: :delete, data: {confirm: "この記事を削除しますか？"} %></td>
        <% end %>
      </tr>
    <% end %>
  </table>

app/views/blogs/new.html.erb
<h1>新規ブログ投稿</h1>

<%= form_for(@blog) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
    <%= f.label :title,"タイトル" %>
    <%= f.text_field :title %>

    <%= f.label :content,"コンテンツ" %>
    <%= f.text_field :content %>

    <%= f.submit "登録", class: "btn btn-success" %>
    <%= link_to "戻る", blogs_path, class: "btn btn-default" %>
<% end %>

app/views/blogs/show.html.erb
<h1>記事詳細</h1>

<p>タイトル：<%= @blog.title %></p>
<p>コンテンツ：<%= @blog.content %></p>

<div class="comment-wrapper border-top mb-10">
  <p class="mt-5">コメント一覧</p>
  <% if logged_in? %>
    <% @comments.each do |c| %>
      <div>
        <%= c.user.name unless c.user.blank? %>
        <%= link_to "削除", blog_comment_path(:blog_id => c.blog_id, :comment_id => c.id), method: :delete %>
        <br>
        <%= c.content %>
      </div>
      <br>
    <% end %>
    <%= form_with(model: [@blog, @comment], local: true) do |f| %>
      <%= f.text_area :content, class: "form-control", rows: 5 %>
      <%= button_tag type: "submit", class: "btn btn-success" do %>
    　  コメントする
      <% end %>
    <% end %>
  <% else %>
    <% @comments.each do |c| %>
      <div>
      <%= c.user.name unless c.user.blank? %>
      <br>
      <%= c.content %>
      </div>
    <% end %>
  <% end %>
</div>

<div>
    <%= link_to "戻る", blogs_path %>
</div>

app/views/blogs/update.html.erb
<h1>Blogs#update</h1>
<p>Find me in app/views/blogs/update.html.erb</p>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
   <ul>
    <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
   </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#headerElement">
        </button>
      </div>
      <div class="collapse navbar-collapse" id="headerElement">
        <ul class="nav navbar-nav">
          <%= link_to "ブログ", blogs_path, class: "navbar-brand" %>
        </ul>
        <ul class="navbar-text navbar-right">
          <% if logged_in? %>
            <%= current_user.name %>
            <%= link_to "プロフィール", current_user %>
            <%= link_to "ログアウト", logout_path, method: :delete %>
          <% else %>
            <%= link_to "ログイン", login_path %>
            <%= link_to "新規会員登録", new_user_path %>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTutorial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
  <%= render 'layouts/header' %>
  <% if flash[:success] %>
    <div class="flash">
      <%= flash[:success] %>
    </div>
  <% end %> 
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>新規会員登録</h1>

  <%= form_for(@user) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
   <p>
   <%= f.label :name,"氏名" %>
   <%= f.text_field :name %>
   </p>
   <p>
   <%= f.label :email,"メールアドレス" %>
   <%= f.text_field :email %>
   </p>
   <p>
   <%= f.label :password_digest,"パスワード" %>
   <%= f.password_field :password %>
   </p>
   <p>
     <%= f.label :password_confirmation, "パスワード確認" %>
     <%= f.password_field :password_confirmation %>
   </p>
   <p>
   <%= f.submit "登録" %>
   </p>
  <% end %>

<div>
    <%= link_to "戻る", blogs_path %>
</div>

app/views/users/show.html.erb
<% if flash[:success] %>
  <p><%= flash[:success] %></p>
<% end %>
<h1>ユーザ詳細</h1>
  <p>
  氏名：<%= @user.name %>
  </p>
  <p>
  メール：<%= @user.email %>
  </p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>